### ISSUE TITLE
flags improvements

### ISSUE THREAD

**Issue by dcaba** [dachad/tcpgoon#14]
I think we can improve how we recover arguments:
* first, we can take advantage of the init function for this, as this example:
https://stackoverflow.com/a/19762274
* But, as a final goal, I'd replace the flags library by something a bit more "serious":
https://github.com/ogier/pflag

As, I think a milestone for this project, is to create debian/rpm packages and a docker image, and allow users to use this tool as any other you may have in your OS, and the default flags in golang are not posix compliant plus they dont support "short letters"...

**Comment by dcaba** [comment]
dismissing creating flags in the init function. This requires all vars to become global (not nice)

**Comment by dcaba** [comment]
https://github.com/spf13/pflag ; previous reference is no longer maintained (it actually does not work well)

**Comment by chadell** [comment]
I would assume this issue is fully addressed by the Merged PR, isn't it?

**Comment by dcaba** [comment]
Yup, unless you find something else to improve on this... Maybe we should
create one to generate the proper documentation / man page?

**Comment by dcaba** [comment]
Oggh, I found this one:
https://github.com/alecthomas/kingpin

Quite better! I'd vote for switching to it!! See this:
https://github.com/alecthomas/kingpin#complex-example

Simple but effective ;)

**Comment by chadell** [comment]
I like it! it has methods that simplifies a lot the code after parsing.

**Comment by dcaba** [comment]
releasing ownership. I'm working in the closure logic (next steps on this become orphan, but i can pick in the future)

**Comment by dcaba** [comment]
another alternative, very common: https://github.com/spf13/cobra

**Comment by chadell** [comment]
working in #38

**Comment by chadell** [comment]
done by #38
