### ISSUE TITLE
Add unit testing to all methods

### ISSUE THREAD

**Issue by chadell** [dachad/tcpgoon#15]
* Add testing to all methods

**Comment by chadell** [comment]
#27 covering tcpconnect package

**Comment by dcaba** [comment]
Proposal:
@dcaba is taking care of end to end tests (close to the dockerization we have been discussing), plus mtcpclient?
@chadell takes care of tcpclient, cmdutil and review of tcpserver?

**Comment by chadell** [comment]
yup 👍

**Comment by dcaba** [comment]
btw, I've detected random errors because of concurrent map writes when executing our current "functional test":
```
=== RUN   TestTcpConnect
127.0.0.1:37748
127.0.0.1:37746
fatal error: concurrent map writes
```
TO bear in mind when refactoring tests...

**Comment by chadell** [comment]
tcpclient done in #27

**Comment by dcaba** [comment]
We are promoting end to end tests implementation in parallel, and we will add testing coverage incrementally, as part of the next PRs we are going to raise
