### ISSUE TITLE
Docker image generation for easy consumption

### ISSUE THREAD

**Issue by dcaba** [dachad/tcpgoon#18]
Generating and sharing docker image (it must be part of the build also for future releases) to run the tool may help its usage. Integrating also with whalebrew could be interesting (https://github.com/bfirsh/whalebrew), and may facilitate integration with travis

Christian, I will pick this one (I cannot initiate just right now, but soon)

**Comment by chadell** [comment]
👍

**Comment by dcaba** [comment]
We do have the first docker image automatically pushed by travis after a merge to master!
https://travis-ci.org/dachad/tcpgoon/builds/306238162
https://hub.docker.com/r/dachad/tcpgoon/tags/
