### ISSUE TITLE
Per connection metrics and some stats in final report

### ISSUE THREAD

**Issue by dcaba** [dachad/tcpgoon#19]
Collecting the time it required an specific connection to dial (so until it becomes effectively established) its a nice metric, we could collect per metric (and incorporate this to the struct representing each connection status?), output it when debug is enabled, but in the normal one, just provide some summaries in the final report (as ping does), with avg/mean/dev...

**Comment by chadell** [comment]
👍

**Comment by chadell** [comment]
PR in #23
