### ISSUE TITLE
Simple version field using the golinker flags

### ISSUE THREAD

**Issue by dcaba** [dachad/tcpgoon#24]
We can add a version field, aligned with the build date / commit-id, quite easily. See:
https://stackoverflow.com/a/11355611

**Comment by chadell** [comment]
working in #43

**Comment by dcaba** [comment]
I think i didnt wrote it, but id use the short version of the commit id,
and id add this flag/property to the binary plus tag the docker image
accordingly too!!!

**Comment by dcaba** [comment]
completed by @chadell . Thanks for the contrib!
