### ISSUE TITLE
Handle partial successful execution

### ISSUE THREAD

**Issue by chadell** [dachad/tcpgoon#26]
We should be able to deal with executions that get partial success due several reasons (stressed server?) and present propers metrics and report.

**Comment by dcaba** [comment]
Are not we doing this already? I recommended you to change the "processing time" so it also tracks failed connections, that will also be represented in the report rather than "0"... I think this should do the trick for now

**Comment by dcaba** [comment]
Was this already covered by https://github.com/dachad/tcpgoon/pull/23 ?

**Comment by chadell** [comment]
yes, covered there
