### ISSUE TITLE
New execution modes?

### ISSUE THREAD

**Issue by dcaba** [dachad/tcpgoon#30]
Or just extra behavior that can be configured just with extra flags?
* current mode with extra options in regards to connections closure-policy?
* open up to X concurrent connections (keeping the old ones), but in less than X seconds (and retrying failed ones)
* "open X connections per second" (keeping previous?) until one fails, so find the actual limit

We should start by creating a proposal of new "options/commands", comparing against just extending what we have, and  see which ones looks cleaner/easier to understand..

**Comment by chadell** [comment]
I will take this

**Comment by chadell** [comment]
we could have this running modes:

- **try-and-forget**: current mode (default one?)
- **try-and-keep**:  open up to X concurrent connections (keeping the old ones), but in less than X seconds (and retrying failed ones), so a mandatory argument for timing should be added in this mode
- **kill-it**:  "open X connections per second" (keeping previous ones) until some of them fails (tolerance?), so find the actual limit of the server

**Comment by dcaba** [comment]
when you say new argument (mode) you mean a command? I don't see the names very intuitive.. and in fact, I'm thinking mapping all these behaviour to a couple of flags may be enough, rather than "isolated modes" / commands:
* connections termination policy: keep/close/other-end-decides
* retry-on-failures: retry-when-dialing/reopen-on-closure
* incremental mode: define time to wait between new connections (current) vs define a new connections rate per second
* program closure policy: fail-when-first-error-found, reach-a-limit and then close, or define an execution time (do what you can in 10 seconds)

  A single PR covering all could be massive. We can divide the following aspects and also balance between us the development.

**Comment by chadell** [comment]
I was thinking on a "mode" flag
We could organize this in several PR, one for each mode
the names I proposed should be simple and short to be used int the command line as mode flags, so we should agree on easy to remember words.
I don't see difference in your 3rd and 4th ones, because this could be adjusted with the current flags.

**Comment by dcaba** [comment]
While this functionality is interesting, no current demand / use case, so closing for now. Would love to see this in the future - we are focusing in other matters now
