### ISSUE TITLE
Error management improvements

### ISSUE THREAD

**Issue by dcaba** [dachad/tcpgoon#7]
And retries should be configurable:
* it may depend on how we are running the tool (in the mode of "open and keep X connections open", retrying makes sense. In the mode of "try to open up to X connections" it may not have sense)

**Comment by chadell** [comment]
we should work on a proper error handling in the code `if err != nil {`...

**Comment by dcaba** [comment]
Do you mind if we close this? I see this as the implementation of the "extra modes" we have been discussing

**Comment by dcaba** [comment]
(reopen if you don't agree ;) )
